config/routes.rb
SampleApp::Application.routes.draw do

  resources :contacts

  resources :newsletters

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  get '/blogs_:content_type' => 'blogs#index', as: 'blogs_content_type'
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :blogs
  root to: 'static_pages#home'
  match '/privacy_and_security', to: 'static_pages#privacy_and_security', via: 'get'
  match '/terms_of_use', to: 'static_pages#terms_of_use', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #match '/help',    to: 'static_pages#help',    via: 'get'
  #match '/about',   to: 'static_pages#about',   via: 'get'
  #match '/contact', to: 'static_pages#contact', via: 'get'


  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/views/layouts/_admin.html.erb
</br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= (t 'admin.admin_management') %></h3>
        </div>
        <div class="panel-body">
          <%= link_to (t 'admin.users'), users_path, class: "btn btn-sm btn-primary" %> |
          <%= link_to (t 'admin.mails'), newsletters_path, class: "btn btn-sm btn-warning" %> |
          <%= link_to (t 'admin.contacts'), contacts_path, class: "btn btn-sm btn-success" %> |
          <%= link_to (t 'admin.site_mobile_version_check'), {:mobile => 0}, class: "btn btn-sm btn-info" %> | | | |

          <%= link_to (t 'admin.new_blog'), new_blog_path, class: "btn btn-sm btn-success" %> |
          <%= link_to (t 'newsletters.new'), new_newsletter_path, class: "btn btn-sm btn-warning" %> | | | |
          <%= link_to (t 'Sign out'), signout_path, method: "delete", class: "btn btn-sm btn-danger" %> |
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.pectorale.com.ua/">www.pectorale.com.ua</a>
    All Rights Reserved, 2014. Created by <a href="http://proalab.com/" target="_blank">Proalab</a>.
  </small>
  <nav>
    <ul>
      <li><%= link_to (I18n.t 'menu.about_us_f'), root_path + "#about_us" %></li>
      <li>|</li>
      <li><%= link_to (I18n.t 'menu.contact_us_f'), root_path + "#contact_us" %></li>
		<!--<li><a href="http://news.railstutorial.org/">News</a></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Ломбард Пектораль", root_path, id: "logo" %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-9">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to (I18n.t 'menu.about_us'), root_path + "#about_us" %></li>
          <li><%= link_to (I18n.t 'menu.contact_us'), root_path + "#contact_us" %></li>
          <li><%= link_to (I18n.t 'menu.finance'), root_path + "#finance" %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myCarousel").carousel({
                interval : 5000,
                pause: false
            });
        });
    </script>
    <!--Google Analytics-->
    <!--Google Analytics-->
    <!--Google Map-->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <%= javascript_include_tag "google_maps" %>
    <!--Google Map-->
  </head>
  <body onload="initialize(), setMarkers()">
    <%= render 'layouts/header' %>
    <%= content = yield %>
    <!--Back To Top Button-->
    <% if content.length > 1200 %>
      <%= link_to("#top") do %>
          <div id="backtotop" style="display: block;">
          </div>
      <% end %>
  <% end %>
  <% if current_user.try(:admin?) %>
      <%= render 'layouts/admin' %>
  <% else %>
  <% end %>
      <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'static_pages/mobile/shim' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <!--Google Analytics-->

    <!--Google Analytics-->
  </head>
  <body>
  <p>
    <% if mobile_device? %>
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
        <%= link_to (I18n.t 'full_site'), {:mobile => 0}, class: "btn btn-lg btn-primary" %>
      </div>
        </div>
      </div>
  <% else %>
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
        <%= link_to (I18n.t 'mobile_site'), {:mobile => 1}, class: "btn btn-lg btn-primary" %>
      </div>
        </div>
      </div>
  <% end %>
  </p>
    <%= render 'static_pages/mobile/header' %>
  <%= content = yield %>
  <!--Back To Top Button-->
  <% if content.length > 1200 %>
      <%= link_to("#top") do %>
          <div id="backtotop" style="display: block;">
          </div>
      <% end %>
  <% end %>
      <div class="container">
      <%= render 'static_pages/mobile/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>